# Generated by Django 4.1.7 on 2023-06-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='realty',
            name='area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='realty',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
