# Generated by Django 4.1.7 on 2023-06-21 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0002_realty_area_realty_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realty',
            name='area',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
