# Generated by Django 4.1.7 on 2023-07-14 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0003_rename_cat_category_managers_catt_and_more'),
        ('realty', '0004_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='realty',
            name='managers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='managers.managers'),
        ),
    ]
