# Generated by Django 4.1.7 on 2023-07-14 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0002_managers_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category_managers',
            old_name='cat',
            new_name='catt',
        ),
        migrations.RenameField(
            model_name='managers',
            old_name='cat',
            new_name='catt',
        ),
    ]
