# Generated by Django 4.1.7 on 2023-07-16 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0003_rename_cat_category_managers_catt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category_managers',
            old_name='catt',
            new_name='cat',
        ),
        migrations.RenameField(
            model_name='managers',
            old_name='catt',
            new_name='cat',
        ),
    ]
