# Generated by Django 4.1.7 on 2023-06-21 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_rerust_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rerust',
            name='img',
        ),
    ]
