# Generated by Django 4.1.7 on 2023-07-14 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0004_rerust_question2'),
    ]

    operations = [
        migrations.AddField(
            model_name='rerust',
            name='id_manager',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
