# Generated by Django 4.1.7 on 2023-07-20 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0006_rerust_object_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rerust',
            name='object_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
